name: CI
on:
  push:
    branches: [master, vb/develop1]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: '1.6'
            os: ubuntu-latest
            arch: x64
          - version: '1.6'
            os: macOS-latest
            arch: x64
          - version: '1.6'
            os: windows-latest
            arch: x64
          - version: '1.6'
            os: ubuntu-latest
            arch: x86
          - version: '1.6'
            os: windows-latest
            arch: x86
          - version: '1'
            os: ubuntu-latest
            arch: x64
          - version: '1'
            os: macOS-latest
            arch: x64
          - version: '1'
            os: windows-latest
            arch: x64
          - version: '1'
            os: ubuntu-latest
            arch: x86
          - version: '1'
            os: windows-latest
            arch: x86
          - version: 'nightly'
            os: ubuntu-latest
            arch: x64
          - version: 'nightly'
            os: macOS-latest
            arch: x64
          - version: 'nightly'
            os: windows-latest
            arch: x64
          - version: 'nightly'
            os: ubuntu-latest
            arch: x86
          - version: 'nightly'
            os: windows-latest
            arch: x86
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Install OSQP_jll.jl from custom repo
        run: |
          julia --project=@. -e 'using Pkg; Pkg.add(url="https://github.com/osqp/OSQP_jll.jl.git")'
        shell: bash  
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          depwarn: error
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
